# Intervalos de Confianza — Práctica 1: Simulación Ad Hoc
**Universidad de los Llanos — Simulación Computacional**

Este notebook calcula, para cada una de las 5 medidas de desempeño, la media muestral, la desviación estándar muestral, la media anchura (*half-width*) y los intervalos de confianza al 95% y al 99%, siguiendo el procedimiento del **Ejemplo 2** de la sección 1.11.1 del Capítulo 1 de [Banks1998].

Se aplica a los dos escenarios de la práctica:
- **Simulación con 20 clientes** (10 corridas / *runs*)
- **Simulación con 200 clientes** (10 corridas / *runs*)

In [1]:
import numpy as np
from scipy import stats
from IPython.display import display, Markdown
import pandas as pd

## Función de cálculo de intervalo de confianza

Implementa las ecuaciones (2), (3) y (4) del Ejemplo 2 de [Banks1998]:

$$\bar{X} = \frac{\sum_{i=1}^{n} X_i}{n} \qquad S^2 = \frac{\sum_{i=1}^{n} X_i^2 - n\bar{X}^2}{n-1} \qquad h = t_{n-1,\,1-\alpha/2}\frac{S}{\sqrt{n}}$$

In [2]:
def confidence_interval(data, alpha, label=""):
    """Calcula media, desviacion estandar muestral, half-width e IC para 'data' con nivel alpha.
    Muestra los resultados en formato Markdown, igual que el Ejemplo 2 de [Banks1998]."""
    reps = len(data)
    confidence = (1 - alpha) * 100

    mean = np.mean(data)
    var = np.var(data, ddof=1)
    desv = np.sqrt(var)

    tval = stats.t.ppf(1 - (alpha / 2), reps - 1)
    hval = tval * (desv / np.sqrt(reps))

    display(Markdown(
        rf"""
**{label}** — ${confidence:.1f}\%$ confidence

$\bar{{X}} = {mean:.4f}$

$S = {desv:.4f}$

$t_{{n-1,1-\frac{{\alpha}}{{2}}}} = t_{{{reps-1},{1-alpha/2}}} = {tval:.4f}$

$h = {hval:.4f}$

Intervalo de confianza : $C.I. = (\bar{{X}}-h , \bar{{X}}+h) = ({mean-hval:.4f}, {mean+hval:.4f})$

---
"""))

    return {
        "label": label,
        "confidence": confidence,
        "mean": mean,
        "S": desv,
        "t": tval,
        "h": hval,
        "ci_low": mean - hval,
        "ci_high": mean + hval,
    }

## 1. Simulación con 20 clientes (10 corridas)

Datos tomados de la hoja **"10 runs"** del archivo `Copia_de_Ejemplo_fila_banco1.xlsx`.

In [3]:
# Datos de las 10 corridas - 20 clientes
avg_time_system_20 = [4.65, 3.6, 4.1, 5.8, 5.0, 5.2, 3.45, 3.35, 4.25, 5.3]
pct_idle_20        = [0.3982, 0.47, 0.4196, 0.27, 0.2347, 0.2613, 0.47, 0.4095, 0.354, 0.29]
avg_wait_cust_20   = [1.25, 0.5, 0.85, 1.9, 1.25, 1.15, 0.3, 0.25, 0.6, 1.25]
frac_wait_20       = [0.3, 0.2, 0.35, 0.4, 0.3, 0.4, 0.15, 0.1, 0.35, 0.4]
avg_wait_waited_20 = [4.167, 2.5, 2.4, 4.75, 4.1, 2.8, 2.0, 2.5, 1.714, 3.125]

df_20 = pd.DataFrame({
    "Run": range(1, 11),
    "Average time in system": avg_time_system_20,
    "Percent idle time": pct_idle_20,
    "Average waiting time per customer": avg_wait_cust_20,
    "Fraction having to wait": frac_wait_20,
    "Average waiting time of those who waited": avg_wait_waited_20,
})
df_20

,Run,Average time in system,Percent idle time,Average waiting time per customer,Fraction having to wait,Average waiting time of those who waited
0,1,4.65,0.3982,1.25,0.30,4.167
1,2,3.60,0.4700,0.50,0.20,2.500
2,3,4.10,0.4196,0.85,0.35,2.400
3,4,5.80,0.2700,1.90,0.40,4.750
4,5,5.00,0.2347,1.25,0.30,4.100
5,6,5.20,0.2613,1.15,0.40,2.800
6,7,3.45,0.4700,0.30,0.15,2.000
7,8,3.35,0.4095,0.25,0.10,2.500
8,9,4.25,0.3540,0.60,0.35,1.714
9,10,5.30,0.2900,1.25,0.40,3.125

### 1.1 Average time in system — 20 clientes

In [4]:
res_ats_20_95 = confidence_interval(avg_time_system_20, 0.05, "Average time in system (20 clientes)")
res_ats_20_99 = confidence_interval(avg_time_system_20, 0.01, "Average time in system (20 clientes)")

**Average time in system (20 clientes)** — $95.0\%$ confidence

$\bar{X} = 4.4700$

$S = 0.8525$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.6099$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (3.8601, 5.0799)$

---

**Average time in system (20 clientes)** — $99.0\%$ confidence

$\bar{X} = 4.4700$

$S = 0.8525$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.8761$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (3.5939, 5.3461)$

---

### 1.2 Percent idle time — 20 clientes

In [5]:
res_pit_20_95 = confidence_interval(pct_idle_20, 0.05, "Percent idle time (20 clientes)")
res_pit_20_99 = confidence_interval(pct_idle_20, 0.01, "Percent idle time (20 clientes)")

**Percent idle time (20 clientes)** — $95.0\%$ confidence

$\bar{X} = 0.3577$

$S = 0.0882$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.0631$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.2946, 0.4209)$

---

**Percent idle time (20 clientes)** — $99.0\%$ confidence

$\bar{X} = 0.3577$

$S = 0.0882$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.0907$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.2670, 0.4484)$

---

### 1.3 Average waiting time per customer — 20 clientes

In [6]:
res_awc_20_95 = confidence_interval(avg_wait_cust_20, 0.05, "Average waiting time per customer (20 clientes)")
res_awc_20_99 = confidence_interval(avg_wait_cust_20, 0.01, "Average waiting time per customer (20 clientes)")

**Average waiting time per customer (20 clientes)** — $95.0\%$ confidence

$\bar{X} = 0.9300$

$S = 0.5224$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.3737$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.5563, 1.3037)$

---

**Average waiting time per customer (20 clientes)** — $99.0\%$ confidence

$\bar{X} = 0.9300$

$S = 0.5224$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.5369$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.3931, 1.4669)$

---

### 1.4 Fraction having to wait — 20 clientes

In [7]:
res_fhw_20_95 = confidence_interval(frac_wait_20, 0.05, "Fraction having to wait (20 clientes)")
res_fhw_20_99 = confidence_interval(frac_wait_20, 0.01, "Fraction having to wait (20 clientes)")

**Fraction having to wait (20 clientes)** — $95.0\%$ confidence

$\bar{X} = 0.2950$

$S = 0.1092$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.0781$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.2169, 0.3731)$

---

**Fraction having to wait (20 clientes)** — $99.0\%$ confidence

$\bar{X} = 0.2950$

$S = 0.1092$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.1122$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.1828, 0.4072)$

---

### 1.5 Average waiting time of those who waited — 20 clientes

In [8]:
res_aww_20_95 = confidence_interval(avg_wait_waited_20, 0.05, "Average waiting time of those who waited (20 clientes)")
res_aww_20_99 = confidence_interval(avg_wait_waited_20, 0.01, "Average waiting time of those who waited (20 clientes)")

**Average waiting time of those who waited (20 clientes)** — $95.0\%$ confidence

$\bar{X} = 3.0056$

$S = 1.0112$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.7234$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (2.2822, 3.7290)$

---

**Average waiting time of those who waited (20 clientes)** — $99.0\%$ confidence

$\bar{X} = 3.0056$

$S = 1.0112$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 1.0392$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (1.9664, 4.0448)$

---

## 2. Simulación con 200 clientes (10 corridas)

Datos tomados de la hoja **"10 runs"** del archivo `Ejemplo_fila_banco_200_clientes.xlsx`.

In [9]:
# Datos de las 10 corridas - 200 clientes
avg_time_system_200 = [4.965, 5.44, 4.835, 5.855, 4.775, 4.995, 5.04, 4.96, 4.565, 4.345]
pct_idle_200        = [0.3511, 0.3348, 0.3436, 0.3156, 0.3557, 0.3706, 0.2968, 0.3033, 0.3849, 0.4055]
avg_wait_cust_200   = [1.425, 1.675, 1.415, 2.31, 1.215, 1.42, 1.475, 1.285, 0.985, 0.995]
frac_wait_200       = [0.35, 0.45, 0.415, 0.455, 0.35, 0.395, 0.42, 0.405, 0.32, 0.3]
avg_wait_waited_200 = [4.0714, 3.7222, 3.4096, 5.0769, 3.4714, 3.5949, 3.5119, 3.1728, 3.0781, 3.3167]

df_200 = pd.DataFrame({
    "Run": range(1, 11),
    "Average time in system": avg_time_system_200,
    "Percent idle time": pct_idle_200,
    "Average waiting time per customer": avg_wait_cust_200,
    "Fraction having to wait": frac_wait_200,
    "Average waiting time of those who waited": avg_wait_waited_200,
})
df_200

,Run,Average time in system,Percent idle time,Average waiting time per customer,Fraction having to wait,Average waiting time of those who waited
0,1,4.965,0.3511,1.425,0.350,4.0714
1,2,5.440,0.3348,1.675,0.450,3.7222
2,3,4.835,0.3436,1.415,0.415,3.4096
3,4,5.855,0.3156,2.310,0.455,5.0769
4,5,4.775,0.3557,1.215,0.350,3.4714
5,6,4.995,0.3706,1.420,0.395,3.5949
6,7,5.040,0.2968,1.475,0.420,3.5119
7,8,4.960,0.3033,1.285,0.405,3.1728
8,9,4.565,0.3849,0.985,0.320,3.0781
9,10,4.345,0.4055,0.995,0.300,3.3167

### 2.1 Average time in system — 200 clientes

In [10]:
res_ats_200_95 = confidence_interval(avg_time_system_200, 0.05, "Average time in system (200 clientes)")
res_ats_200_99 = confidence_interval(avg_time_system_200, 0.01, "Average time in system (200 clientes)")

**Average time in system (200 clientes)** — $95.0\%$ confidence

$\bar{X} = 4.9775$

$S = 0.4243$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.3035$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (4.6740, 5.2810)$

---

**Average time in system (200 clientes)** — $99.0\%$ confidence

$\bar{X} = 4.9775$

$S = 0.4243$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.4360$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (4.5415, 5.4135)$

---

### 2.2 Percent idle time — 200 clientes

In [11]:
res_pit_200_95 = confidence_interval(pct_idle_200, 0.05, "Percent idle time (200 clientes)")
res_pit_200_99 = confidence_interval(pct_idle_200, 0.01, "Percent idle time (200 clientes)")

**Percent idle time (200 clientes)** — $95.0\%$ confidence

$\bar{X} = 0.3462$

$S = 0.0351$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.0251$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.3211, 0.3713)$

---

**Percent idle time (200 clientes)** — $99.0\%$ confidence

$\bar{X} = 0.3462$

$S = 0.0351$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.0361$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.3101, 0.3822)$

---

### 2.3 Average waiting time per customer — 200 clientes

In [12]:
res_awc_200_95 = confidence_interval(avg_wait_cust_200, 0.05, "Average waiting time per customer (200 clientes)")
res_awc_200_99 = confidence_interval(avg_wait_cust_200, 0.01, "Average waiting time per customer (200 clientes)")

**Average waiting time per customer (200 clientes)** — $95.0\%$ confidence

$\bar{X} = 1.4200$

$S = 0.3786$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.2709$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (1.1491, 1.6909)$

---

**Average waiting time per customer (200 clientes)** — $99.0\%$ confidence

$\bar{X} = 1.4200$

$S = 0.3786$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.3891$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (1.0309, 1.8091)$

---

### 2.4 Fraction having to wait — 200 clientes

In [13]:
res_fhw_200_95 = confidence_interval(frac_wait_200, 0.05, "Fraction having to wait (200 clientes)")
res_fhw_200_99 = confidence_interval(frac_wait_200, 0.01, "Fraction having to wait (200 clientes)")

**Fraction having to wait (200 clientes)** — $95.0\%$ confidence

$\bar{X} = 0.3860$

$S = 0.0534$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.0382$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.3478, 0.4242)$

---

**Fraction having to wait (200 clientes)** — $99.0\%$ confidence

$\bar{X} = 0.3860$

$S = 0.0534$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.0549$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (0.3311, 0.4409)$

---

### 2.5 Average waiting time of those who waited — 200 clientes

In [14]:
res_aww_200_95 = confidence_interval(avg_wait_waited_200, 0.05, "Average waiting time of those who waited (200 clientes)")
res_aww_200_99 = confidence_interval(avg_wait_waited_200, 0.01, "Average waiting time of those who waited (200 clientes)")

**Average waiting time of those who waited (200 clientes)** — $95.0\%$ confidence

$\bar{X} = 3.6426$

$S = 0.5770$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.975} = 2.2622$

$h = 0.4127$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (3.2299, 4.0553)$

---

**Average waiting time of those who waited (200 clientes)** — $99.0\%$ confidence

$\bar{X} = 3.6426$

$S = 0.5770$

$t_{n-1,1-\frac{\alpha}{2}} = t_{9,0.995} = 3.2498$

$h = 0.5929$

Intervalo de confianza : $C.I. = (\bar{X}-h , \bar{X}+h) = (3.0497, 4.2355)$

---

## 3. Tabla resumen comparativa (20 vs 200 clientes)

Se compara la desviación estándar muestral $S$ y el rango del intervalo de confianza ($2h$) para cada medida de desempeño, en ambos escenarios y niveles de confianza, con el fin de responder: **¿cuál combinación de número de clientes, repeticiones y porcentaje de confianza tiene la menor desviación estándar de la muestra y el menor rango del intervalo de confianza?**

In [15]:
resultados = [
    res_ats_20_95, res_ats_20_99, res_ats_200_95, res_ats_200_99,
    res_pit_20_95, res_pit_20_99, res_pit_200_95, res_pit_200_99,
    res_awc_20_95, res_awc_20_99, res_awc_200_95, res_awc_200_99,
    res_fhw_20_95, res_fhw_20_99, res_fhw_200_95, res_fhw_200_99,
    res_aww_20_95, res_aww_20_99, res_aww_200_95, res_aww_200_99,
]

resumen = pd.DataFrame(resultados)
resumen["rango_IC"] = resumen["ci_high"] - resumen["ci_low"]
resumen = resumen[["label", "confidence", "mean", "S", "h", "ci_low", "ci_high", "rango_IC"]]
resumen.columns = ["Medida", "% Confianza", "Media", "S", "half-width (h)", "IC inf.", "IC sup.", "Rango IC"]
resumen.round(4)

,Medida,% Confianza,Media,S,half-width (h),IC inf.,IC sup.,Rango IC
0,Average time in system (20 clientes),95.0,4.4700,0.8525,0.6099,3.8601,5.0799,1.2197
1,Average time in system (20 clientes),99.0,4.4700,0.8525,0.8761,3.5939,5.3461,1.7522
2,Average time in system (200 clientes),95.0,4.9775,0.4243,0.3035,4.6740,5.2810,0.6070
3,Average time in system (200 clientes),99.0,4.9775,0.4243,0.4360,4.5415,5.4135,0.8721
4,Percent idle time (20 clientes),95.0,0.3577,0.0882,0.0631,0.2946,0.4209,0.1263
5,Percent idle time (20 clientes),99.0,0.3577,0.0882,0.0907,0.2670,0.4484,0.1814
6,Percent idle time (200 clientes),95.0,0.3462,0.0351,0.0251,0.3211,0.3713,0.0502
7,Percent idle time (200 clientes),99.0,0.3462,0.0351,0.0361,0.3101,0.3822,0.0721
8,Average waiting time per customer (20 clientes),95.0,0.9300,0.5224,0.3737,0.5563,1.3037,0.7474
9,Average waiting time per customer (20 clientes),99.0,0.9300,0.5224,0.5369,0.3931,1.4669,1.0737
10,Average waiting time per customer (200 clientes),95.0,1.4200,0.3786,0.2709,1.1491,1.6909,0.5417
11,Average waiting time per customer (200 clientes),99.0,1.4200,0.3786,0.3891,1.0309,1.8091,0.7782
12,Fraction having to wait (20 clientes),95.0,0.2950,0.1092,0.0781,0.2169,0.3731,0.1562
13,Fraction having to wait (20 clientes),99.0,0.2950,0.1092,0.1122,0.1828,0.4072,0.2244
14,Fraction having to wait (200 clientes),95.0,0.3860,0.0534,0.0382,0.3478,0.4242,0.0764
15,Fraction having to wait (200 clientes),99.0,0.3860,0.0534,0.0549,0.3311,0.4409,0.1097
16,Average waiting time of those who waited (20 c...,95.0,3.0056,1.0112,0.7234,2.2822,3.7290,1.4468
17,Average waiting time of those who waited (20 c...,99.0,3.0056,1.0112,1.0392,1.9664,4.0448,2.0785
18,Average waiting time of those who waited (200 ...,95.0,3.6426,0.5770,0.4127,3.2299,4.0553,0.8255
19,Average waiting time of those who waited (200 ...,99.0,3.6426,0.5770,0.5929,3.0497,4.2355,1.1859

In [16]:
# Fila con el menor S y menor rango de IC en toda la tabla
print("Menor desviación estándar (S):")
display(resumen.loc[[resumen["S"].idxmin()]].round(4))

print("\nMenor rango de intervalo de confianza:")
display(resumen.loc[[resumen["Rango IC"].idxmin()]].round(4))

Menor desviación estándar (S):

,Medida,% Confianza,Media,S,half-width (h),IC inf.,IC sup.,Rango IC
6,Percent idle time (200 clientes),95.0,0.3462,0.0351,0.0251,0.3211,0.3713,0.0502

Menor rango de intervalo de confianza:

,Medida,% Confianza,Media,S,half-width (h),IC inf.,IC sup.,Rango IC
6,Percent idle time (200 clientes),95.0,0.3462,0.0351,0.0251,0.3211,0.3713,0.0502